### ISSUE TITLE
Comparison of Common Lisp Logging Libraries

### ISSUE THREAD

**Issue by flintforge** [sabracrolleton/sabracrolleton.github.io#11]
Hi.

Pleasant and informative reading. 

2 typos:
[ \### Debugging with log5](https://github.com/sabracrolleton/sabracrolleton.github.io/blob/cfbf5c6f41bd62fc2dd2370372738137cccee8f3/logging-comparison.md?plain=1#L1517) → `**Debugging with log5**`
   
[[...] for a file named](https://github.com/sabracrolleton/sabracrolleton.github.io/blob/cfbf5c6f41bd62fc2dd2370372738137cccee8f3/logging-comparison.md?plain=1#L1678) *logging.config*

Cheers !

**Comment by sabracrolleton** [comment]
Thank you.
