### ISSUE TITLE
typos 1↔2

### ISSUE THREAD

**Issue by Devon7** [sabracrolleton/sabracrolleton.github.io#4]
①  **Helper Libraries** has two footnotes with the same number.
②  **Table 5: Default Mapping Json to CL** incorrectly shows results for `{"a": 2}`
③  **Table 51: Conformity Testing - Must Accept Library** "Json-streams has the dubious distinction of not accepting any" yet the table shows json-streams accepting 93, not 0.

**Comment by sabracrolleton** [comment]
Thank you! Fixed.
